### ISSUE TITLE
Travel time on transit vs. car to hospitals, stores, schools, etc. -- pin bin values?

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#95] opened 2021-06-03 15:54 UTC
This was a prior request so I'm not sure if it got lost - reissuing here:
Legend for Transit-Car ratios of travel times as set, rather than percentile-based, bins: <1, <2, <3, <4, >4. I think it's easy to understand what equal travel time vs. travel time that's 4x as long means, and there is a certain value to identifying the areas that have consistently competitive transit service - as fast or faster than traveling by car.

**Comment by mlbtc** [comment] 2021-06-03 15:55
related to this, the DC Economic Region travel time to hospital by car vs. transit is showing less than -1 for the top 20% of block groups. What does -1 mean in this context? 

http://ec2-3-21-125-103.us-east-2.compute.amazonaws.com:5000/map/dc?key=hospitals_M_t1_PM_autoY_fareN&zone=er&date=2021-02-21&demo=none

**Comment by wklumpen** [comment] 2021-06-04 13:59
Partial duplicate of #24.

The second comment sounds like a bug in the data. I'll treat this issue as the bugfix, and we can continue the discussion on fixed bins at Issue #24.

**Comment by wklumpen** [comment] 2021-06-04 14:20
Bug was an issue with using unfiltered data for the legend labels (the colors were correct). I also reconfigured the label indicating the values are ratios to make the legend more friendly. Will be reflected in v.1.0.0

**Closed by wklumpen** 2021-06-04 14:20 UTC
Labels: bug, map
